it("Add client", async () => {
        await clientPage.openForm()
        await clientPage.setSurname("LastOF ")
        await clientPage.setName("Test")
        await clientPage.setMiddleName("Testovich")
        await clientPage.setEmail("sysomebodysomebody@gmail.com")
        await clientPage.setPhone("996786780301")
        await browser.pause(2000)
        await clientPage.setProfession()
        await clientPage.setGender()
        await clientPage.setBirthday("01.01.2001")
        await clientPage.save()
        await browser.pause(3000)
        await browser.acceptAlert()
        await browser.pause(5000)

})